#!/usr/bin/env bash
set -euo pipefail

dry_run=false
install_plugins=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)
      dry_run=true
      ;;
    --plugins)
      install_plugins=true
      ;;
    *)
      printf 'usage: %s [--dry-run] [--plugins]\n' "$0" >&2
      exit 2
      ;;
  esac
  shift
done

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
codex_home="${CODEX_HOME:-$HOME/.codex}"
agents_home="${AGENTS_HOME:-$HOME/.agents}"
claude_home="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
timestamp="$(date +%Y%m%d-%H%M%S)"
backup_root="$codex_home/backups/ai-$timestamp-$$"
plugin_manifest="$repo_root/codex-plugins.txt"
config_source="$repo_root/ai-home/codex/config.toml"
rules_source="$repo_root/ai-home/codex/rules/default.rules"
claude_settings="$claude_home/settings.json"
github_root="$HOME/github"
rendered_config=""
claude_rules=""
claude_current=""
claude_rendered=""
json_tool=""

if "$install_plugins"; then
  if [[ ! -f "$plugin_manifest" ]]; then
    printf 'error: plugin manifest does not exist: %s\n' "$plugin_manifest" >&2
    exit 1
  fi
  if ! "$dry_run" && ! command -v codex >/dev/null 2>&1; then
    printf 'error: codex is required when using --plugins\n' >&2
    exit 1
  fi
fi

run() {
  if "$dry_run"; then
    printf '+'
    printf ' %q' "$@"
    printf '\n'
  else
    "$@"
  fi
}

cleanup() {
  local scratch

  for scratch in "$rendered_config" "$claude_rules" "$claude_current" "$claude_rendered"; do
    if [[ -n "$scratch" && -f "$scratch" ]]; then
      rm -f -- "$scratch"
    fi
  done
}
trap cleanup EXIT

ensure_parent() {
  run mkdir -p "$(dirname "$1")"
}

resolve_path() {
  local path="$1"
  local directory
  local hops=0
  local link_target

  while [[ -L "$path" ]]; do
    hops=$((hops + 1))
    if ((hops > 64)); then
      printf 'error: too many symbolic-link hops: %s\n' "$1" >&2
      return 2
    fi

    if ! directory="$(cd -P "$(dirname "$path")" && pwd)"; then
      return 1
    fi
    if ! link_target="$(readlink "$path")"; then
      return 1
    fi
    if [[ "$link_target" == /* ]]; then
      path="$link_target"
    else
      path="$directory/$link_target"
    fi
  done

  if [[ -d "$path" ]]; then
    if ! directory="$(cd -P "$path" && pwd)"; then
      return 1
    fi
    printf '%s\n' "$directory"
    return
  fi

  if ! directory="$(cd -P "$(dirname "$path")" && pwd)"; then
    return 1
  fi
  printf '%s/%s\n' "$directory" "$(basename "$path")"
}

backup_path_for() {
  local target="$1"

  case "$target" in
    "$codex_home"/*) printf '%s/%s\n' "$backup_root" "${target#"$codex_home"/}" ;;
    "$agents_home"/*) printf '%s/agents/%s\n' "$backup_root" "${target#"$agents_home"/}" ;;
    "$claude_home"/*) printf '%s/claude/%s\n' "$backup_root" "${target#"$claude_home"/}" ;;
    *)
      printf 'error: managed target is outside the managed homes: %s\n' "$target" >&2
      exit 1
      ;;
  esac
}

link_managed_path() {
  local source="$1"
  local target="$2"

  if [[ ! -e "$source" ]]; then
    printf 'error: managed source does not exist: %s\n' "$source" >&2
    exit 1
  fi

  ensure_parent "$target"

  if [[ -L "$target" ]]; then
    local resolved_source
    local resolved_target=""
    local resolve_status=0

    if ! resolved_source="$(resolve_path "$source")"; then
      return 1
    fi

    if resolved_target="$(resolve_path "$target")"; then
      resolve_status=0
    else
      resolve_status=$?
    fi

    if ((resolve_status != 0 && resolve_status != 2)); then
      return "$resolve_status"
    fi

    if ((resolve_status == 0)) && [[ "$resolved_target" == "$resolved_source" ]]; then
      printf 'already linked: %s\n' "$target"
      return
    fi
  fi

  if [[ -e "$target" || -L "$target" ]]; then
    ensure_parent "$(backup_path_for "$target")"
    run mv "$target" "$(backup_path_for "$target")"
    printf 'backed up: %s -> %s\n' "$target" "$(backup_path_for "$target")"
  fi

  run ln -s "$source" "$target"
  printf 'linked: %s -> %s\n' "$target" "$source"
}

append_trusted_project() {
  local config_file="$1"
  local project_path="$2"
  local escaped_path="$project_path"
  local table_header

  if [[ "$project_path" =~ [[:cntrl:]] ]]; then
    printf 'error: project path contains unsupported control characters: %q\n' \
      "$project_path" >&2
    exit 1
  fi

  escaped_path="${escaped_path//\\/\\\\}"
  escaped_path="${escaped_path//\"/\\\"}"
  table_header="[projects.\"$escaped_path\"]"

  if grep -Fqx "$table_header" "$config_file"; then
    return
  fi

  printf '\n%s\ntrust_level = "trusted"\n' "$table_header" >>"$config_file"
}

render_managed_config() {
  local git_marker
  local project_path

  rendered_config="$(mktemp "${TMPDIR:-/tmp}/ai-config.XXXXXX")"
  cp "$config_source" "$rendered_config"
  printf '\n# Generated by the AI installer. Rerun it after adding repositories.\n' \
    >>"$rendered_config"
  append_trusted_project "$rendered_config" "$github_root"

  if [[ -d "$github_root" ]]; then
    while IFS= read -r -d '' git_marker; do
      project_path="${git_marker%/.git}"
      append_trusted_project "$rendered_config" "$project_path"
    done < <(
      find "$github_root" \
        \( -name .git -o -name node_modules -o -name .venv -o -name venv \
        -o -name target -o -name build -o -name dist \) -prune \
        -name .git -print0
    )
  fi
}

install_managed_config() {
  local target="$1"

  ensure_parent "$target"

  if [[ -f "$target" && ! -L "$target" ]] && cmp -s "$rendered_config" "$target"; then
    printf 'already installed: %s\n' "$target"
    return
  fi

  if [[ -e "$target" || -L "$target" ]]; then
    ensure_parent "$(backup_path_for "$target")"
    run mv "$target" "$(backup_path_for "$target")"
    printf 'backed up: %s -> %s\n' "$target" "$(backup_path_for "$target")"
  fi

  run cp "$rendered_config" "$target"
  printf 'installed: %s\n' "$target"
}

derive_claude_rules() {
  local command_name

  while IFS= read -r command_name; do
    printf 'Bash(%s *)\nPowerShell(%s *)\n' "$command_name" "$command_name"
  done < <(
    sed -n 's/^prefix_rule(pattern=\["\([^"]*\)"\], decision="allow")$/\1/p' "$rules_source" |
      awk '!seen[$0]++'
  )
}

select_json_tool() {
  local candidate

  for candidate in python3 python; do
    command -v "$candidate" >/dev/null 2>&1 || continue
    # A non-functional python3 shim can sit on PATH, so confirm it actually runs.
    "$candidate" --version >/dev/null 2>&1 || continue
    json_tool="$candidate"
    return
  done
}

render_claude_settings() {
  local rules="$1"
  local current="$2"
  local rendered="$3"

  "$json_tool" - "$rules" "$current" "$rendered" <<'PYTHON'
import json
import pathlib
import sys

rules_path, current_path, rendered_path = (pathlib.Path(p) for p in sys.argv[1:4])
rules = [line for line in rules_path.read_text().splitlines() if line]
settings = json.loads(current_path.read_text())
permissions = settings.setdefault("permissions", {})
allow = permissions.setdefault("allow", [])
present = set(allow)

for rule in rules:
    if rule not in present:
        allow.append(rule)
        present.add(rule)

rendered_path.write_text(json.dumps(settings, indent=2, ensure_ascii=False) + "\n")
PYTHON
}

install_claude_settings() {
  local target="$claude_settings"

  select_json_tool

  if [[ -z "$json_tool" ]]; then
    printf 'warning: python3 is required to merge %s; skipping\n' "$target" >&2
    return
  fi

  claude_rules="$(mktemp "${TMPDIR:-/tmp}/ai-claude-rules.XXXXXX")"
  claude_current="$(mktemp "${TMPDIR:-/tmp}/ai-claude-current.XXXXXX")"
  claude_rendered="$(mktemp "${TMPDIR:-/tmp}/ai-claude-rendered.XXXXXX")"

  derive_claude_rules >"$claude_rules"

  if [[ ! -s "$claude_rules" ]]; then
    printf 'error: no allow rules derived from %s\n' "$rules_source" >&2
    exit 1
  fi

  if [[ -f "$target" && -s "$target" ]]; then
    cp "$target" "$claude_current"
  else
    printf '{}\n' >"$claude_current"
  fi

  if ! render_claude_settings "$claude_rules" "$claude_current" "$claude_rendered"; then
    printf 'error: could not merge managed permissions into %s\n' "$target" >&2
    exit 1
  fi

  if [[ -f "$target" && ! -L "$target" ]] && cmp -s "$claude_rendered" "$target"; then
    printf 'already current: %s\n' "$target"
    return
  fi

  ensure_parent "$target"

  if [[ -e "$target" || -L "$target" ]]; then
    ensure_parent "$(backup_path_for "$target")"
    run cp "$target" "$(backup_path_for "$target")"
    printf 'backed up: %s -> %s\n' "$target" "$(backup_path_for "$target")"
  fi

  run cp "$claude_rendered" "$target"
  printf 'merged managed permissions: %s\n' "$target"
}

install_recommended_plugins() {
  local plugin

  while IFS= read -r plugin || [[ -n "$plugin" ]]; do
    [[ -n "$plugin" ]] || continue
    run codex plugin add "$plugin"
  done <"$plugin_manifest"
}

render_managed_config
link_managed_path "$repo_root/ai-home/AGENTS.md" "$codex_home/AGENTS.md"
install_managed_config "$codex_home/config.toml"
link_managed_path "$repo_root/ai-home/codex/rules" "$codex_home/rules"

for profile in "$repo_root"/ai-home/codex/*.config.toml; do
  [[ -f "$profile" ]] || continue
  link_managed_path "$profile" "$codex_home/$(basename "$profile")"
done

link_managed_path "$repo_root/ai-home/AGENTS.md" "$claude_home/CLAUDE.md"
install_claude_settings

for skill_dir in "$repo_root"/.agents/skills/*; do
  [[ -d "$skill_dir" ]] || continue
  link_managed_path "$skill_dir" "$agents_home/skills/$(basename "$skill_dir")"
  link_managed_path "$skill_dir" "$claude_home/skills/$(basename "$skill_dir")"
done

if "$install_plugins"; then
  install_recommended_plugins
fi

if "$dry_run"; then
  printf 'dry run complete\n'
else
  printf 'installation complete. Restart Codex and Claude Code to reload configuration.\n'
fi
