#!/usr/bin/env bash
set -euo pipefail

# Generate mdBook skill reference files from the official guide
# Source: https://github.com/rust-lang/mdBook (guide/ directory)
#
# Usage: ./scripts/generate-references.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REFS_DIR="$SKILL_DIR/references"
MDBOOK_REPO="https://github.com/rust-lang/mdBook.git"
WORK_DIR=$(mktemp -d)

cleanup() { rm -rf "$WORK_DIR"; }
trap cleanup EXIT

echo "==> Cloning mdBook (sparse, guide/ only)..."
git clone --depth 1 --filter=blob:none --sparse --quiet "$MDBOOK_REPO" "$WORK_DIR/mdbook"
git -C "$WORK_DIR/mdbook" sparse-checkout set guide/src/

GUIDE="$WORK_DIR/mdbook/guide/src"

MDBOOK_COMMIT=$(git -C "$WORK_DIR/mdbook" rev-parse --short HEAD)
MDBOOK_DATE=$(git -C "$WORK_DIR/mdbook" log -1 --format=%ci)

echo "==> mdBook commit: $MDBOOK_COMMIT ($MDBOOK_DATE)"

mkdir -p "$REFS_DIR"

# ── Helpers ────────────────────────────────────────────────────────────

copy_page() {
    local src="$1" dst="$REFS_DIR/$2" url="$3"
    if [[ ! -f "$src" ]]; then
        echo "  WARN: $(basename "$src") not found, skipping"
        return
    fi
    {
        echo "<!-- source: $url -->"
        echo "<!-- repo: rust-lang/mdBook commit $MDBOOK_COMMIT ($MDBOOK_DATE) -->"
        echo "<!-- auto-generated by scripts/generate-references.sh - DO NOT EDIT MANUALLY -->"
        echo ""
        cat "$src"
    } > "$dst"
    echo "  OK: $2"
}

merge_pages() {
    local dst="$REFS_DIR/$1" header="$2" url="$3" repo="$4"
    shift 4
    {
        echo "<!-- source: $url -->"
        echo "<!-- repo: rust-lang/mdBook commit $MDBOOK_COMMIT ($MDBOOK_DATE) -->"
        echo "<!-- auto-generated by scripts/generate-references.sh - DO NOT EDIT MANUALLY -->"
        echo ""
        echo "# $header"
        echo ""
        for src in "$@"; do
            if [[ -f "$src" ]]; then
                cat "$src"
                echo ""
                echo "---"
                echo ""
            else
                echo "  WARN: $(basename "$src") not found, skipping from merge" >&2
            fi
        done
    } > "$dst"
    echo "  OK: $1 (merged)"
}

echo ""
echo "==> Generating reference files..."

# ── Guide overview ─────────────────────────────────────────────────────

copy_page "$GUIDE/README.md" \
    "overview.md" \
    "https://rust-lang.github.io/mdBook/"

copy_page "$GUIDE/SUMMARY.md" \
    "summary.md" \
    "https://rust-lang.github.io/mdBook/"

# ── Getting Started ────────────────────────────────────────────────────

copy_page "$GUIDE/guide/installation.md" \
    "installation.md" \
    "https://rust-lang.github.io/mdBook/guide/installation.html"

copy_page "$GUIDE/guide/creating.md" \
    "creating-a-book.md" \
    "https://rust-lang.github.io/mdBook/guide/creating.html"

copy_page "$GUIDE/guide/reading.md" \
    "reading-books.md" \
    "https://rust-lang.github.io/mdBook/guide/reading.html"

# ── CLI ────────────────────────────────────────────────────────────────

merge_pages "cli.md" "mdBook CLI Reference" \
    "https://rust-lang.github.io/mdBook/cli/" "rust-lang/mdBook" \
    "$GUIDE/cli/README.md" \
    "$GUIDE/cli/init.md" \
    "$GUIDE/cli/build.md" \
    "$GUIDE/cli/watch.md" \
    "$GUIDE/cli/serve.md" \
    "$GUIDE/cli/test.md" \
    "$GUIDE/cli/clean.md" \
    "$GUIDE/cli/completions.md" \
    "$GUIDE/cli/arg-watcher.md"

# ── Format / Configuration ────────────────────────────────────────────

copy_page "$GUIDE/format/summary.md" \
    "summary-format.md" \
    "https://rust-lang.github.io/mdBook/format/summary.html"

merge_pages "configuration.md" "mdBook Configuration (book.toml)" \
    "https://rust-lang.github.io/mdBook/format/configuration/" "rust-lang/mdBook" \
    "$GUIDE/format/configuration/README.md" \
    "$GUIDE/format/configuration/general.md" \
    "$GUIDE/format/configuration/preprocessors.md" \
    "$GUIDE/format/configuration/renderers.md" \
    "$GUIDE/format/configuration/environment-variables.md"

copy_page "$GUIDE/format/markdown.md" \
    "markdown.md" \
    "https://rust-lang.github.io/mdBook/format/markdown.html"

copy_page "$GUIDE/format/mathjax.md" \
    "mathjax.md" \
    "https://rust-lang.github.io/mdBook/format/mathjax.html"

copy_page "$GUIDE/format/mdbook.md" \
    "mdbook-specific.md" \
    "https://rust-lang.github.io/mdBook/format/mdbook.html"

# ── Theme ──────────────────────────────────────────────────────────────

merge_pages "theme.md" "mdBook Theme Customization" \
    "https://rust-lang.github.io/mdBook/format/theme/" "rust-lang/mdBook" \
    "$GUIDE/format/theme/README.md" \
    "$GUIDE/format/theme/index-hbs.md" \
    "$GUIDE/format/theme/syntax-highlighting.md" \
    "$GUIDE/format/theme/editor.md"

# ── For Developers ─────────────────────────────────────────────────────

merge_pages "for-developers.md" "mdBook for Developers (Preprocessors & Backends)" \
    "https://rust-lang.github.io/mdBook/for_developers/" "rust-lang/mdBook" \
    "$GUIDE/for_developers/README.md" \
    "$GUIDE/for_developers/preprocessors.md" \
    "$GUIDE/for_developers/backends.md"

# ── Continuous Integration ─────────────────────────────────────────────

copy_page "$GUIDE/continuous-integration.md" \
    "continuous-integration.md" \
    "https://rust-lang.github.io/mdBook/continuous-integration.html"

# ── Write version metadata ────────────────────────────────────────────

echo ""
echo "==> Writing metadata..."

cat > "$REFS_DIR/.wiki-version" <<EOF
commit='$MDBOOK_COMMIT'
date='$MDBOOK_DATE'
EOF

TOTAL=$(find "$REFS_DIR" -name '*.md' | wc -l)
echo "==> Done! Generated $TOTAL reference files from mdBook commit $MDBOOK_COMMIT"
echo "    Output: $REFS_DIR/"
